set_property IOSTANDARD LVCMOS33 [get_ports bck_0]
set_property IOSTANDARD LVCMOS33 [get_ports mclk_0]
set_property IOSTANDARD LVCMOS33 [get_ports din_0]
set_property IOSTANDARD LVCMOS33 [get_ports dout_0]
set_property IOSTANDARD LVCMOS33 [get_ports lrck_0]
set_property PACKAGE_PIN D20 [get_ports din_0]
set_property PACKAGE_PIN B19 [get_ports dout_0]
set_property PACKAGE_PIN A20 [get_ports lrck_0]
set_property PACKAGE_PIN H17 [get_ports mclk_0]
set_property PACKAGE_PIN C20 [get_ports bck_0]

set_property PACKAGE_PIN G19 [get_ports data_0]
set_property IOSTANDARD LVCMOS33 [get_ports data_0]
set_property PACKAGE_PIN J19 [get_ports latch_0]
set_property IOSTANDARD LVCMOS33 [get_ports latch_0]
set_property IOSTANDARD LVCMOS33 [get_ports clk_0]
set_property PACKAGE_PIN G20 [get_ports clk_0]
set_property IOSTANDARD LVCMOS33 [get_ports reset_0]
set_property PACKAGE_PIN M18 [get_ports reset_0]
set_property C_CLK_INPUT_FREQ_HZ 300000000 [get_debug_cores dbg_hub]
set_property C_ENABLE_CLK_DIVIDER false [get_debug_cores dbg_hub]
set_property C_USER_SCAN_CHAIN 1 [get_debug_cores dbg_hub]
connect_debug_port dbg_hub/clk [get_nets clk]

set_property CLOCK_DEDICATED_ROUTE FALSE [get_nets clk_0_IBUF]
set_property CLOCK_DEDICATED_ROUTE FALSE [get_nets latch_0_IBUF]
